Very close to a working UEFI
This PR series does not address secure boot, which looks like
an entire area of pain.

The problem is that virtualbox does not store the `nvram` of the
virtual machine. To solve this problem, placing a bootloader in
`/efi/boot` in a `standard` location enables booting even when
the boot order, which is stored in the `nvram` is lost.

This is much closer, appearing to only need default video mode.

```
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF BEAE3398
ProtectUefiImageCommon - 0xBE32B240
  - 0x00000000BDFA2000 - 0x00000000000D4000
[Variable]: Rewritten a preexisting variable(0x00000006) with different attributes(0x00000007) - 605DAB50-E046-4300-ABB6-3DD810DD8B23:MokListRT
[Variable]: Rewritten a preexisting variable(0x00000006) with different attributes(0x00000007) - 605DAB50-E046-4300-ABB6-3DD810DD8B23:MokListXRT
[Variable]: Rewritten a preexisting variable(0x00000006) with different attributes(0x00000007) - 605DAB50-E046-4300-ABB6-3DD810DD8B23:SbatLevelRT
[Variable]: Rewritten a preexisting variable(0x00000006) with different attributes(0x00000007) - 605DAB50-E046-4300-ABB6-3DD810DD8B23:MokListTrustedRT
InstallProtocolInterface: 605DAB50-E046-4300-ABB6-3DD810DD8B23 BE054020
FSOpen: Open '\EFI\debian\grubx64.efi' Success
Welcome to GRUB!
error: no suitable video mode found.

                        GNU GRUB  version 2.06-3~deb11u5

 ����������������������������������������������������������������������������Ŀ
 �*Debian GNU/Linux                                                           �
 � Advanced options for Debian GNU/Linux                                      �
 � UEFI Firmware Settings                                                     �
 �                                                                            �
 �                                                                            �
 �                                                                            �
 �                                                                            �
 �                                                                            �
 �                                                                            �
 �                                                                            �
 �                                                                            �
 �                                                                            �
 ������������������������������������������������������������������������������

      Use the ^ and v keys to select which entry is highlighted.
      Press enter to boot the selected OS, `e' to edit the commands
      before booting or `c' for a command-line. ESC to return previous
      menu.
   The highlighted entry will be executed automatically in 0s.
  Booting `Debian GNU/Linux'

Loading Linux 5.10.0-23-amd64 ...
Loading initial ramdisk ...
error: no suitable video mode found.
Booting in blind mode
CpuDxe: 5-Level Paging = 0
MpInitChangeApLoopCallback() done!
SetUefiImageMemoryAttributes - 0x00000000BF8E9000 - 0x0000000000006000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x00000000BF8E3000 - 0x0000000000006000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x00000000BF8DC000 - 0x0000000000007000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x00000000BF8D6000 - 0x0000000000006000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x00000000BF8C6000 - 0x0000000000010000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x00000000BF8C1000 - 0x0000000000005000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x00000000BF8BB000 - 0x0000000000006000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x00000000BF8B7000 - 0x0000000000004000 (0x0000000000000008)
SetUefiImageMemoryAttributes - 0x00000000BF8B3000 - 0x0000000000004000 (0x0000000000000008)
```